packages:
  - "apps/*"

onlyBuiltDependencies:
  - esbuild
  - prisma
  - "@prisma/engines"
  - "@prisma/client"

allowBuilds:
  esbuild: true
  prisma: true
  "@prisma/engines": true
  "@prisma/client": true
  msgpackr-extract: false
  workerd: false
